name: programmer-changes

# ```
# on:
#   schedule:
#     - cron: '30 5 * * 1,3'
#     - cron: '30 5 * * 2,4'

# jobs:
#   test_schedule:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Not on Monday or Wednesday
#         if: github.event.schedule != '30 5 * * 1,3'
#         run: echo "This step will be skipped on Monday and Wednesday"
#       - name: Every time
#         run: echo "This step will always run"
# ```

on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'

jobs:
  detect_changes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Puppeteer
        run: sudo apt-get install -y chromium-browser
      - name: Yarn
        run: yarn install
      - name: Run
        working-directory: ./workers/programmers-changes
        run: yarn start
        env:
          CRECO_STORAGE_PAT: ${{ secrets.CRECO_STORAGE_PAT }}
          TTAPI_TOKEN: ${{ secrets.TTAPI_TOKEN }}
